# Generated by Django 5.0.6 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='update_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('aim', models.TextField(default=True)),
            ],
        ),
    ]
